# Generated by Django 4.2 on 2023-04-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Resources', models.TextField(null=True)),
            ],
        ),
    ]
