# Generated by Django 4.2 on 2023-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingBasics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='Resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
