# Generated by Django 4.2 on 2023-04-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='Name',
        ),
    ]
